export * from './menuIcon'
export * from './mainSectionIcon'
export * from './dashIcon'
export * from './facebookIcon'
export * from './instagramIcon'
export * from './twitterIcon'
export * from './arrowIcon'
export * from './starIcon'
